### ISSUE TITLE
Change notation type on multiple dependencies

### ISSUE THREAD

**Issue by reebow** [platan/idea-gradle-dependencies-formatter#38]
Hi,
I was wondering if it is possible to change the format of multiple dependency at once, from map to string notation?

Best Regards,
Tim

**Comment by platan** [comment]
Hi @reebow!

Thanks for a contact. Unfortunately currently it is not possible to change a notation type for multiple dependencies at once. But I have to admit that this would be really useful. 
It should be simpler to achieve than https://github.com/platan/idea-gradle-dependencies-formatter/issues/6. I will try to add such option, but I cannot give you any specific date now.

**Comment by platan** [comment]
Fixed in version 0.6.0 https://plugins.jetbrains.com/plugin/7937-gradle-dependencies-formatter/versions/
