### ISSUE TITLE
Can't sort dependencies in allprojects or subprojects block

### ISSUE THREAD

**Issue by flandia** [platan/idea-gradle-dependencies-formatter#39]

**Comment by platan** [comment]
Hi @FlandiaYingman!

Thank you for reaching out to me. I can confirm that currently is is possible to sort dependencies inside root `dependencies` block only. 

Would you like use the `Sort Gradle dependencies` action to sort all `dependencies` blocks (root, in `allprojects` and in `subprojects`) at one once or to have separate actions for every location? In my opinion one action for sorting all `dependencies` blocks would be sufficient.

**Comment by flandia** [comment]
@platan 
I prefer your opinion too, because I think there is no need to separate actions.

**Comment by platan** [comment]
Fixed in version 0.6.0 https://plugins.jetbrains.com/plugin/7937-gradle-dependencies-formatter/versions/
