### ISSUE TITLE
Hyphens in Maven variable names get pasted with spaces surrounding them in the Gradle dependency

### ISSUE THREAD

**Issue by platan** [platan/idea-gradle-dependencies-formatter#4]
Reported by @banana-ben in https://github.com/platan/idea-gradle-dependencies-formatter/issues/3#issuecomment-353977742:

hyphens in Maven variable names get pasted with spaces surrounding them in the Gradle dependency, ie:
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-jdbc</artifactId>
	<version>${spring-boot-version}</version>
</dependency>
```

becomes
`compile "org.springframework.boot:spring-boot-starter-jdbc:${spring - boot - version}"`

**Comment by platan** [comment]
Hyphen represents an arithmetic operator in Groovy. So you can't use `${spring-boot-version}` to read value of property with a key `spring-boot-version`. But you can read the value using `property()` method:
`compile "org.springframework.boot:spring-boot-starter-jdbc:${property('spring-boot-version')}"`
Here https://discuss.gradle.org/t/trying-to-define-global-ext-properties-version-for-dependencies/11159/2 you can find more info about variables with 'dot' in name (similar case to hyphen in name) and ways to define them. But probably the simplest solution is to use variable names without hyphens (with _ instead of - ([3,221 code results at GitHub](https://github.com/search?l=Gradle&q=%22spring_boot_version%22&type=Code&utf8=%E2%9C%93)) or using camel case([47,415 code results at Gitub](https://github.com/search?l=Gradle&q=%22springbootversion%22&type=Code&utf8=%E2%9C%93))).

These extra spaces added around hyphens is not a bug in 'Gradle dependencies formatter' plugin. It's a feature of IntelliJ Groovy plugin ;-) If you paste 
```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-jdbc</artifactId>
	<version>${spring-boot-version}</version>
</dependency>
``` 
into double quoted string in groovy file you will get:
```groovy
"<dependency>\n" +
"\t<groupId>org.springframework.boot</groupId>\n" +
"\t<artifactId>spring-boot-starter-jdbc</artifactId>\n" +
"\t<version>${spring - boot - version}</version>\n" +
"</dependency>"
```
You can disable this feature in `Settings > Editor > Code Style > Groovy > Spaces > Around Operators > additive Operators (+, -)`

**Comment by mxwlsavard** [comment]
Oh good catch. I didn't notice this because I was just removing those variables in the gradle file, my bad! And thanks again for looking into these issues, this plugin is super helpful!
