### ISSUE TITLE
map to string notation with variables isn't handled properly

### ISSUE THREAD

**Issue by bj0** [platan/idea-gradle-dependencies-formatter#42]
If you try to convert a map notation that uses a variable (not a variable in a string) to string notation, it does not treat it as a variable.  This results in the following:

    testImplementation group: 'org.mockito', name: 'mockito-core', version: mockitoVersion

becoming

    testImplementation 'org.mockito:mockito-core:mockitoVersion'

Which requries fixing the variable reference as well as replacing single quotes with double quotes.

**Comment by platan** [comment]
Thanks @bj0 for reporting this. This actually is a common use case, but I didn't test it. I will try to fix this in the next weeks.

**Comment by platan** [comment]
Fixed in version 0.6.0 https://plugins.jetbrains.com/plugin/7937-gradle-dependencies-formatter/versions/
