### ISSUE TITLE
Support for Android Studio Projects

### ISSUE THREAD

**Issue by 1951FDG** [platan/idea-gradle-dependencies-formatter#5]
Hi,

Is it possible to enable support for Android Studio Projects, it currently works by isolating the dependencies and then copying back, but this is quite annoying, support for nested  dependencies in gradle file for example `android { dependencies { } }`

**Comment by platan** [comment]
@1951FDG it is possible to add support for this case. Can you describe what would you like to achieve and what is not working? 
Could you please provide an example of such `android { dependencies { } }` block and/or a documentation of this feature? I cannot find in documentation https://developer.android.com/studio/intro/index.html. This notation is new for me.

**Comment by 1951FDG** [comment]
Hi, this is undocumented I believe, I started working on my first project, still quite new to Android development.

In this example the dependencies block is nested within the android block: https://raw.githubusercontent.com/sds100/NvidiaGpuMonitor/master/app/build.gradle

But no mention is made in: https://developer.android.com/studio/build/dependencies.html

Both ways work though, but the standard way seems to be, to include the dependencies outside of the android block.

**Comment by platan** [comment]
Thanks for explanation. Taking into account fact that this feature is not documented I think is not worth to add support for this case. 
You can switch to the standard way of declaring dependencies and enjoy all features of Gradle dependencies formatter plugin.

**Comment by 1951FDG** [comment]
Yes, I've done that, thanks, if I ever encounter any official documentation on this, I will inform you!
